@uri=http://localhost:3000

GET {{uri}}/products?search=product1 HTTP/1.1
###
POST {{uri}}/products HTTP/1.1
content-type: application/json

{
  "name": "product1",
  "price": 100,
  "description": "product1 description"
}

###
GET {{uri}}/products HTTP/1.1
content-type: application/json
